+incdir+../../src/globals/
+incdir+../../src/hvl_top/test/sequences/master_sequences/
+incdir+../../src/hvl_top/master/
+incdir+../../src/hdl_top/master_agent_bfm/ 
+incdir+../../src/hvl_top/env/virtual_sequencer/
+incdir+../../src/hvl_top/test/virtual_sequences/
+incdir+../../src/hvl_top/env
+incdir+../../src/hvl_top/slave
+incdir+../../src/hvl_top/test/sequences/slave_sequences/
+incdir+../../src/hvl_top/test
+incdir+../../src/hdl_top/slave_agent_bfm
+incdir+../../src/hdl_top/spi_interface
../../src/globals/spi_globals_pkg.sv
../../src/hvl_top/master/spi_master_pkg.sv
../../src/hvl_top/slave/spi_slave_pkg.sv
../../src/hvl_top/test/sequences/master_sequences/spi_master_seq_pkg.sv
../../src/hvl_top/test/sequences/slave_sequences/spi_slave_seq_pkg.sv
../../src/hvl_top/env/spi_env_pkg.sv
../../src/hvl_top/test/virtual_sequences/spi_virtual_seq_pkg.sv
../../src/hvl_top/test/test_pkg.sv
../../src/hdl_top/spi_interface/spi_if.sv
../../src/hdl_top/master_agent_bfm/master_driver_bfm.sv
../../src/hdl_top/master_agent_bfm/master_monitor_bfm.sv
../../src/hdl_top/master_agent_bfm/master_agent_bfm.sv
../../src/hdl_top/slave_agent_bfm/slave_driver_bfm.sv
../../src/hdl_top/slave_agent_bfm/slave_monitor_bfm.sv
../../src/hdl_top/slave_agent_bfm/slave_agent_bfm.sv
../../src/hdl_top/hdl_top.sv
../../src/hvl_top/hvl_top.sv 
